#!/bin/sh

set -e

export AUTOSSH_PATH=`which ssh`


if which autossh > /dev/null 2>&1; then
    # I don't know why the sleep 1 is necessary, but without the
    # delay, the other side just freezes up
    autossh -M 0 -t awk "sleep 1 && screen -x"
else
    ssh -t awk "screen -x"
fi
