#!/usr/bin/python3

# Use gettings-diff to see what settings differ from defaults

import os.path
import sys
from typing import NamedTuple

import dbus
import gi
gi.require_version("Gdk", "4.0")
gi.require_version("Gtk", "4.0")
from gi.repository import Gdk, Gtk

sys.path.insert(0, os.path.join(os.path.dirname(os.path.realpath(__file__)), "lib"))
import configlib
from configlib import get, gset, logDo

wm = None

def install_extension(id):
    bus = dbus.SessionBus()
    proxy = bus.get_object("org.gnome.Shell.Extensions", "/org/gnome/Shell/Extensions")
    manager = dbus.Interface(proxy, "org.gnome.Shell.Extensions")

    # installed_extensions is a dict keyed by extension ID.
    installed_extensions = manager.ListExtensions()
    if id in installed_extensions:
        info = installed_extensions[id]
        if info["enabled"]:
            print(f"Extension {id} already installed and enabled")
            return True
        print(f"Extension {id} already installed")
    else:
        if not logDo(f"Installing {id}"):
            # Can't dry-run enabling without installing
            return False
        configlib.checkApply("InstallRemoteExtension")
        manager.InstallRemoteExtension(id)
        info = manager.GetExtensionInfo(id)
        # I think installing automatically enables, but if not, we'll fall
        # through to enabling.
        if info["enabled"]:
            return True

    if not logDo(f"Enabling {id}"):
        return False
    configlib.checkApply("EnableExtension")
    manager.EnableExtension(id)

    return True

class Accel(NamedTuple):
    key: int
    mods: Gdk.ModifierType

    @classmethod
    def parse(cls, str):
        ok, key, mods = Gtk.accelerator_parse(str)
        if not ok:
            raise ValueError(f"Invalid accelerator: {str}" )
        return cls(key=key, mods=mods)

    def __str__(self) -> str:
        return Gtk.accelerator_name(self.key, self.mods)

def set_view():
    # Dark mode, monospace font, Ptyxis
    configlib.set_common()

    # Switch workspaces on all displays
    gset("org.gnome.mutter", "workspaces-only-on-primary", False)

    # Turn off alert sound
    gset("org.gnome.desktop.sound", "event-sounds", False)

    # Use transparent dash
    if configlib.has_schema("org.gnome.shell.extensions.dash-to-panel"):
        gset("org.gnome.shell.extensions.dash-to-panel", "trans-use-custom-opacity", True)
    else:
        print("dash-to-panel not installed; skipping its settings")

def set_input():
    # Control key
    gset("org.gnome.desktop.input-sources", "xkb-options", ["caps:ctrl_modifier"])

    # Tap to click
    gset("org.gnome.desktop.peripherals.touchpad", "tap-to-click", True)

    if wm == "gnome":
        # Focus follows mouse
        gset("org.gnome.desktop.wm.preferences", "focus-mode", "sloppy")
    elif wm == "paperwm":
        # Click to focus because PaperWM interacts poorly with sloppy focus
        gset("org.gnome.desktop.wm.preferences", "focus-mode", "click")

def set_keys():
    # Workspace key bindings
    # https://unix.stackexchange.com/questions/677878/supernumber-key-combos-remapping-in-gnome-40-switch-workspaces-instead-of-laun
    for i in range(1, 10):
        # Clear default "switch to application" bindings
        gset("org.gnome.shell.keybindings", f"switch-to-application-{i}", [])
        # Set switch to workspace and move to workspace
        gset("org.gnome.desktop.wm.keybindings",
             f"switch-to-workspace-{i}", [f'<Super>{i}'],
             f"move-to-workspace-{i}", [f'<Super><Shift>{i}'])

    # WM=specific key bindings
    def gsetWM(schema, key, gnome=None, paperwm=None):
        if wm == "gnome":
            gset(schema, key, gnome)
        elif wm == "paperwm":
            gset(schema, key, paperwm)
    # Disable maximize-vertically, which doesn't make much sense in PaperWM.
    gsetWM("org.gnome.desktop.wm.keybindings",
           "maximize-vertically", gnome='<Super>space', paperwm=[])
    # Conflicts with <Super>up/down
    gsetWM("org.gnome.desktop.wm.keybindings",
           "maximize", paperwm=[])
    gsetWM("org.gnome.desktop.wm.keybindings",
           "unmaximize", paperwm=[])
    # Conflicts with <Super>h
    gsetWM("org.gnome.desktop.wm.keybindings",
           "minimize", paperwm=[])
    # Conflicts with <Shift><Super>(arrow)
    for dir in ["up", "down", "left", "right"]:
        gsetWM("org.gnome.desktop.wm.keybindings",
               f"move-to-monitor-{dir}", paperwm=[])
    # Conflicts with <Super>l
    gsetWM("org.gnome.settings-daemon.plugins.media-keys",
           "screensaver", paperwm=["<Super>q"])
    # Conflicts with <Super>Left, <Super>Right
    gsetWM("org.gnome.mutter.keybindings",
           "toggle-tiled-left", paperwm=[])
    gsetWM("org.gnome.mutter.keybindings",
           "toggle-tiled-right", paperwm=[])

    # Custom keybindings. Note that this will clobber any existing custom
    # bindings. It's annoying to just add or check for one.
    gset("org.gnome.settings-daemon.plugins.media-keys",
         "custom-keybindings", ['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/'])
    gset("org.gnome.settings-daemon.plugins.media-keys.custom-keybinding",
         "name", "Terminal",
         "command", "x-terminal-emulator",
         "binding", "<Super>Return",
         path="/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/")

def set_paperwm():
    if wm != "paperwm":
        print("Skipping paperwm setup because of --wm setting")
        return

    id = "paperwm@paperwm.github.com"
    if not install_extension(id):
        # Dry run didn't install, so we can't do much
        print("Skipping paperwm setup")
        return

    # Basic settings
    gset("org.gnome.shell.extensions.paperwm",
         "disable-topbar-styling", True,
         "show-window-position-bar", False,
         # The default top- and bottom-of-screen margin is really big.
         # Make just enough room to see the 10px border.
         "vertical-margin", 12,
         "vertical-margin-bottom", 12,
         extension=id)

    # Key bindings
    def addKeyBinding(name, kb):
        kbs = get("org.gnome.shell.extensions.paperwm.keybindings",
                  name, extension=id).get_strv()
        kb = Accel.parse(kb)
        if kb not in map(Accel.parse, kbs):
            kbs.append(str(kb))
        gset("org.gnome.shell.extensions.paperwm.keybindings", name, kbs, extension=id)
    def rmKeyBinding(name, kb):
        kbs = get("org.gnome.shell.extensions.paperwm.keybindings",
                name, extension=id).get_strv()
        kb = Accel.parse(kb)
        kbs = [kb1 for kb1 in kbs if Accel.parse(kb1) != kb]
        gset("org.gnome.shell.extensions.paperwm.keybindings", name, kbs, extension=id)
    for dir, key in [("down", "j" ), ("left", "h" ), ("right", "l" ), ("up", "k")]:
        addKeyBinding(f"switch-{dir}", f"<Super>{key}")
        addKeyBinding(f"move-{dir}", f"<Shift><Super>{key}")
    rmKeyBinding("new-window", "<Super>Return") # Conflicts with Terminal keybinding

def set_notifications():
    # Make notifications appear in the bottom right and slide up from
    # the bottom.
    id = "notification-banner-reloaded@marcinjakubowski.github.com"
    if not install_extension(id):
        print("Skipping setup of notifications")
        return
    gset("org.gnome.shell.extensions.notification-banner-reloaded",
         "anchor-horizontal", 1,
         "anchor-vertical", 1,
         "animation-direction", 3,
         extension=id)

def add_args(parser):
    parser.add_argument("--wm", choices=["paperwm", "gnome"])

def post_parse(args):
    global wm
    wm = args.wm

configlib.main([
    set_view,
    set_input,
    set_keys,
    set_paperwm,
    set_notifications,
], add_args, post_parse)
