#!/bin/zsh

GARGS=()
while [[ $1 == -* ]]; do
    GARGS=($GARGS $1)
    shift
done

PROG=$1
shift

echo set args ${(q)*} > /tmp/gdb-args-$$
echo shell rm /tmp/gdb-args-$$ >> /tmp/gdb-args-$$

exec gdb $GARGS $PROG -x /tmp/gdb-args-$$
