#!/bin/zsh

LOCKFILE=~/.getmail/dont-be-stupid

(
    if flock -x -n 9; then
        getmail $*
    else
        echo "Lock file exists; not running getmail"
        echo
        echo "'ps auxw | grep getmail | grep -v grep' says:"
        ps auxw | grep getmail | grep -v grep
    fi
) 9>$LOCKFILE
