#!/bin/zsh

set -e

STYLE=autossh

if mount | grep 'on [/a-z]*/n/music '; then
    echo "Unmounting"
    /sbin/umount.cifs -l ~/n/music
fi

# SSH-tunneled connection
FWD="-L localhost:4445:localhost:445 awakening"
if [[ $STYLE == autossh ]]; then
    export AUTOSSH_PATH=`which ssh`
    SSHCMD="$STYLE -M 0 -Nf $FWD"
else
    SSHCMD="$STYLE -Nf $FWD"
fi
PID=`ps w -C $STYLE | grep -- $FWD | awk '{print $1}'`
if [[ -z $PID ]]; then
    echo "Creating SSH tunnel"
    eval $SSHCMD
elif [[ $PID != *[^0-9]* ]]; then
    if [[ $STYLE == autossh ]]; then
        echo "Reconnecting old SSH tunnel ($PID)"
        kill -USR1 $PID
    else
        echo "Closing old SSH tunnel ($PID)"
        kill $PID
        echo "Creating new SSH tunnel"
        eval $SSHCMD
    fi
else
    echo "Confused when trying to find old SSH tunnels ($PID)"
    exit 1
fi

echo "Mounting"
/sbin/mount.cifs //localhost/music ~/n/music -o username=amthrax,uid=amthrax,gid=amthrax,port=4445,iocharset=utf8
