#!/bin/zsh

set -e

if mount | grep 'on [/a-z]*/n/music '; then
    echo "Unmounting"
    /sbin/umount.cifs ~/n/music
fi

# SSH-tunneled connection
SSHCMD="autossh -Nf -L localhost:4445:localhost:445 awakening"
PID=`ps axw | grep $SSHCMD | grep -v grep | awk '{print $1}'`
if [[ ! -z $PID ]]; then
    if [[ $PID != *[^0-9]* ]]; then
        echo "Closing old SSH tunnel ($PID)"
        kill $PID
    else
        echo "Confused when trying to find old SSH tunnels ($PID)"
        exit 1
    fi
fi
echo "Creating SSH tunnel"
eval $SSHCMD

echo "Mounting"
/sbin/mount.cifs //localhost/music ~/n/music -o username=amthrax,uid=amthrax,gid=amthrax,port=4445
