#!/usr/bin/zsh

# This script fixes up a bug in postscript files that include graphics
# produced by idraw.  See
# https://bugzilla.redhat.com/bugzilla/show_bug.cgi?id=74633 for
# information on the bug.

if [[ $#argv != 2 ]]; then
    echo Usage: $0 infile outfile
    exit 1;
fi

BADLINE="/descender fontDict begin 0 \\[FontBBox\\] 1 get FontMatrix end"

if ( grep -q "^${BADLINE}$" $1 ); then
    sed 's,\[FontBBox\],/FontBBox load,' < $1 > $2
    echo 'fixed';
else;
    echo 'idraw error not found'
    exit 1;
fi

