#!/usr/bin/zsh

SPAM=()
HAM=()
for d in $(find ~/Maildir \( -name cur -o -name new -o -name tmp \) -prune -o \( -type d -print \) | sort); do
    if [[ ! -d $d/cur || ! -d $d/new || ! -d $d/tmp ]]; then
        continue
    fi
    case `basename $d` in
        spam)
            SPAM=($SPAM $d/cur $d/new);;
        INBOX|spam*|virus*|reuse|Trash|Sent|Drafts)
            ;;
        *)
            HAM=($HAM $d/cur $d/new);;
    esac
done

EXTRA=
if [[ -t 1 ]]; then
    ISATTY=1
    EXTRA="--progress"
fi

echo "[$(date)] Scanning spam"
sa-learn $EXTRA --spam $SPAM

echo "[$(date)] Scanning ham"
sa-learn $EXTRA --ham $HAM

COUNT=$(ls -1 $SPAM | wc -l)
if (( $COUNT >= 5000 )); then
    SPAMDIR=~/Maildir/spam
    OUTNUM=1
    while [[ -f $SPAMDIR.$OUTNUM ]]; do
        OUTNUM=$(( OUTNUM + 1 ))
    done
    echo "[$(date)] Moving $COUNT spam to $SPAMDIR.$OUTNUM"
    mv -T $SPAMDIR $SPAMDIR.$OUTNUM
    mu-mkmdir $SPAMDIR
    touch $SPAMDIR/.nobackup
fi

echo "[$(date)] Done"
