#!/bin/zsh

set -e

SPAM=${HOME}/Mail/spam
BATCHSIZE=5000

# Get an idea of how much spam there is
echo "Counting beans..."
COUNT=$(formail -l x -s < $SPAM | grep ^From | wc -l)

echo "$COUNT messages in $SPAM"

OUTNUM=1

while [[ -f $SPAM.$OUTNUM ]]; do
    OUTNUM=$(( OUTNUM + 1 ))
done

START=0
OUTNUMSTART=$OUTNUM
while (( START + BATCHSIZE <= COUNT )); do
    OUTBOX=$SPAM.$OUTNUM
    echo "Sending $BATCHSIZE messages starting at $START to $OUTBOX"
    if [[ -f $OUTBOX ]]; then
        echo "Error: $OUTBOX exists"
        exit 1
    fi
    formail +$START -$BATCHSIZE -s < $SPAM > $OUTBOX.tmp
    START=$(( START + BATCHSIZE ))
    OUTNUM=$(( OUTNUM + 1 ))
done

if (( START == 0 )); then
    echo "Nothing to be done"
else
    # XXX Really, this should use locking, but it's just spam
    echo "Keeping last $(( COUNT - START )) messages starting at $START"
    formail +$START -s < $SPAM > $SPAM.tmp

    echo "Committing..."
    OUTNUMEND=$OUTNUM
    OUTNUM=$OUTNUMSTART
    while (( OUTNUM < OUTNUMEND )); do
        OUTBOX=$SPAM.$OUTNUM
        echo "$OUTBOX"
        mv $OUTBOX.tmp $OUTBOX
        OUTNUM=$(( OUTNUM + 1 ))
    done

    echo "$SPAM"
    mv $SPAM.tmp $SPAM
fi
