#!/bin/env zsh

# Find the real ssh
REALSSH=`whence -a ssh | grep -A1 $0 | sed 1d`

# Do the key dance
EXTRA=
ssh-add -l &> /dev/null
LISTRES=$?
if [[ $LISTRES == 1 ]]; then	# No keys in agent
    # Look for a graphical askpass
    for X in ssh-askpass x11-ssh-askpass gtk2-ssh-askpass; do
	if whence $X &> /dev/null; then
	    SSH_ASKPASS=$X
	    break
	fi
    done
    # Add the user's key
    if [[ -n $DISPLAY && -n $SSH_ASKPASS ]]; then
	# Use the graphical askpass
	ssh-add < /dev/null
    else
	# Use the terminal
	unset SSH_ASKPASS
	ssh-add
    fi
    ADDRES=$?
    if [[ $ADDRES != 0 ]]; then
	# Adding failed, so don't ask again
	EXTRA=(-o 'PubkeyAuthentication no');
    fi
elif [[ $LISTRES == 2 ]]; then
    echo I could not find an ssh agent
    # I'd rather be asked my real password at this point
    EXTRA=(-o 'PubkeyAuthentication no');
fi

# Start the real ssh
$REALSSH $EXTRA $*
