#!/bin/zsh

set -e

if [[ $UID != 0 ]]; then
    echo "Must be run as root"
    exit 1
fi

REPOSITORIES=(amthrax sysfiles)

REPDIR=/z/svn

for R in $REPOSITORIES; do
    svn-hot-backup --archive-type=gz $REPDIR/$R .
done
